package main

import (
"fmt"
"image/jpeg"
"image/png"
"net/http"
"time"
)

func setupAPI() {
http.HandleFunc("/api/convert/png-to-jpg", handlePngToJpg)
http.HandleFunc("/api/pdf/merge", handleMockProcess)
http.HandleFunc("/api/pdf/compress", handleMockProcess)
http.HandleFunc("/api/pdf/to-word", handleMockProcess)
http.HandleFunc("/api/pdf/to-excel", handleMockProcess)
}

func handleMockProcess(w http.ResponseWriter, r *http.Request) {
err := r.ParseMultipartForm(50 << 20)
if err != nil {
http.Error(w, "Failed to parse form", http.StatusBadRequest)
return
}
time.Sleep(1 * time.Second) // Simulate processing time
w.Header().Set("Content-Type", "text/plain")
w.Header().Set("Content-Disposition", "attachment; filename=dummy_result.txt")
w.Write([]byte("This is a dummy output generated by the Kit Go Backend.\nReal processing features here are still to be implmented!"))
}

func handlePngToJpg(w http.ResponseWriter, r *http.Request) {
if r.Method != http.MethodPost {
http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
return
}

err := r.ParseMultipartForm(50 << 20)
if err != nil {
http.Error(w, "Failed to parse form", http.StatusBadRequest)
return
}

file, header, err := r.FormFile("image")
if err != nil {
http.Error(w, "Image file is required", http.StatusBadRequest)
return
}
defer file.Close()

img, err := png.Decode(file)
if err != nil {
http.Error(w, "Failed to decode PNG. Ensure the file is a valid PNG.", http.StatusBadRequest)
return
}

w.Header().Set("Content-Type", "image/jpeg")
w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.jpg\"", header.Filename))

opts := &jpeg.Options{Quality: 90}
err = jpeg.Encode(w, img, opts)
if err != nil {
http.Error(w, "Failed to encode JPEG", http.StatusInternalServerError)
return
}

fmt.Printf("Successfully converted %s from PNG to JPG\n", header.Filename)
}
