package main

import (
	"fmt"
	"image/jpeg"
	"image/png"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
)

func setupAPI() {
	http.HandleFunc("/api/convert/png-to-jpg", handlePngToJpg)
	http.HandleFunc("/api/pdf/merge", handleMockProcess)
	http.HandleFunc("/api/pdf/compress", handleCompressPDF)
	http.HandleFunc("/api/pdf/to-word", handleMockProcess)
	http.HandleFunc("/api/pdf/to-excel", handleMockProcess)
}

func handleMockProcess(w http.ResponseWriter, r *http.Request) {
	err := r.ParseMultipartForm(50 << 20)
	if err != nil {
		http.Error(w, "Failed to parse form", http.StatusBadRequest)
		return
	}
	time.Sleep(1 * time.Second) // Simulate processing time
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("Content-Disposition", "attachment; filename=dummy_result.txt")
	w.Write([]byte("This is a dummy output generated by the Kit Go Backend.\nReal processing features here are still to be implmented!"))
}

func handlePngToJpg(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	err := r.ParseMultipartForm(50 << 20)
	if err != nil {
		http.Error(w, "Failed to parse form", http.StatusBadRequest)
		return
	}

	file, header, err := r.FormFile("image")
	if err != nil {
		http.Error(w, "Image file is required", http.StatusBadRequest)
		return
	}
	defer file.Close()

	img, err := png.Decode(file)
	if err != nil {
		http.Error(w, "Failed to decode PNG. Ensure the file is a valid PNG.", http.StatusBadRequest)
		return
	}

	w.Header().Set("Content-Type", "image/jpeg")
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s.jpg\"", header.Filename))

	opts := &jpeg.Options{Quality: 90}
	err = jpeg.Encode(w, img, opts)
	if err != nil {
		http.Error(w, "Failed to encode JPEG", http.StatusInternalServerError)
		return
	}

	fmt.Printf("Successfully converted %s from PNG to JPG\n", header.Filename)
}

func handleCompressPDF(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	err := r.ParseMultipartForm(50 << 20)
	if err != nil {
		http.Error(w, "Failed to parse form", http.StatusBadRequest)
		return
	}

	file, header, err := r.FormFile("file")
	if err != nil {
		file, header, err = r.FormFile("image") // fallback based on frontend
		if err != nil {
			http.Error(w, "PDF file is required", http.StatusBadRequest)
			return
		}
	}
	defer file.Close()

	// Write the uploaded file to a temporary file
	tmpInput, err := os.CreateTemp("", "input-*.pdf")
	if err != nil {
		http.Error(w, "Failed to create temp input file", http.StatusInternalServerError)
		return
	}
	defer os.Remove(tmpInput.Name())

	if _, err := io.Copy(tmpInput, file); err != nil {
		tmpInput.Close()
		http.Error(w, "Failed to save uploaded file", http.StatusInternalServerError)
		return
	}
	tmpInput.Close()

	// Create temp output file path
	tmpOutput, err := os.CreateTemp("", "output-*.pdf")
	if err != nil {
		http.Error(w, "Failed to create temp output file", http.StatusInternalServerError)
		return
	}
	tmpOutput.Close() // Will be overwritten by pdfcpu
	defer os.Remove(tmpOutput.Name())

	// Run pdfcpu to compress the PDF
	conf := model.NewDefaultConfiguration()
	// Apply optimization natively in-process
	err = api.OptimizeFile(tmpInput.Name(), tmpOutput.Name(), conf)
	if err != nil {
		fmt.Printf("pdfcpu error: %v\n", err)
		http.Error(w, "Failed to compress PDF natively. Ensure it is a valid PDF.", http.StatusInternalServerError)
		return
	}

	// Serve the compressed PDF
	compressedFile, err := os.Open(tmpOutput.Name())
	if err != nil {
		http.Error(w, "Failed to open processed file", http.StatusInternalServerError)
		return
	}
	defer compressedFile.Close()

	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="compressed_%s"`, header.Filename))

	_, err = io.Copy(w, compressedFile)
	if err != nil {
		fmt.Printf("Error sending compressed PDF: %v\n", err)
	} else {
		fmt.Printf("Successfully compressed %s\n", header.Filename)
	}
}
